export const now_playing_movies=
[
{
"adult": false,
"backdrop_path": "/xlkclSE4aq7r3JsFIJRgs21zUew.jpg",
"genre_ids": [
    27,
    53
],
"id": 1034541,
"original_language": "en",
"original_title": "Terrifier 3",
"overview": "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
"popularity": 3997.131,
"poster_path": "/63xYQj1BwRFielxsBDXvHIJyXVm.jpg",
"release_date": "2024-10-09",
"title": "Terrifier 3",
"video": false,
"vote_average": 7.336,
"vote_count": 298
},
{
"adult": false,
"backdrop_path": "/9oYdz5gDoIl8h67e3ccv3OHtmm2.jpg",
"genre_ids": [
    27,
    878,
    53
],
"id": 933260,
"original_language": "en",
"original_title": "The Substance",
"overview": "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
"popularity": 2129.397,
"poster_path": "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
"release_date": "2024-09-07",
"title": "The Substance",
"video": false,
"vote_average": 7.3,
"vote_count": 1009
},
{
"adult": false,
"backdrop_path": "/plH6vmlExhkNsxO56DKIzO3oC2O.jpg",
"genre_ids": [
    53,
    12,
    28,
    878
],
"id": 1196470,
"original_language": "fr",
"original_title": "Survivre",
"overview": "A couple celebrates their son’s birthday in the middle of the ocean on their boat. A violent storm hits and it brings up hungry creatures from the depths and they fight for their survival.",
"popularity": 1682.472,
"poster_path": "/7fR3KxswtY8OHHZuOUB9td58CRX.jpg",
"release_date": "2024-06-19",
"title": "Survive",
"video": false,
"vote_average": 4.6,
"vote_count": 25
},
{
"adult": false,
"backdrop_path": "/xi1VSt3DtkevUmzCx2mNlCoDe74.jpg",
"genre_ids": [
    35,
    14,
    27
],
"id": 917496,
"original_language": "en",
"original_title": "Beetlejuice Beetlejuice",
"overview": "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Betelgeuse, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
"popularity": 1040.617,
"poster_path": "/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg",
"release_date": "2024-09-04",
"title": "Beetlejuice Beetlejuice",
"video": false,
"vote_average": 7.187,
"vote_count": 1609
},
{
"adult": false,
"backdrop_path": "/uLqNGzJwnj8JKkKuRM2dHWJKCtc.jpg",
"genre_ids": [
    28,
    27,
    53
],
"id": 1029235,
"original_language": "en",
"original_title": "Azrael",
"overview": "In a world where no one speaks, a devout female hunts down a young woman who has escaped her imprisonment. Recaptured by its ruthless leaders, Azrael is due to be sacrificed to pacify an ancient evil deep within the surrounding wilderness.",
"popularity": 1100.796,
"poster_path": "/qpdFKDvJS7oLKTcBLXOaMwUESbs.jpg",
"release_date": "2024-09-27",
"title": "Azrael",
"video": false,
"vote_average": 6.1,
"vote_count": 104
},
{
"adult": false,
"backdrop_path": "/bAO9hLGRWOJMUFXmKwa4kST6I5N.jpg",
"genre_ids": [
    28,
    35,
    80
],
"id": 616446,
"original_language": "en",
"original_title": "Brothers",
"overview": "A reformed criminal's attempt at going straight is derailed when he reunites with his sanity-testing twin brother on a road trip for the score of a lifetime. Dodging bullets, the law, and an overbearing mother along the way, they must heal their severed family bond before they end up killing each other.",
"popularity": 928.33,
"poster_path": "/Akweo95FGyDpucYVT81h0SbX8Ky.jpg",
"release_date": "2024-10-10",
"title": "Brothers",
"video": false,
"vote_average": 6.3,
"vote_count": 115
},
{
"adult": false,
"backdrop_path": "/3m0j3hCS8kMAaP9El6Vy5Lqnyft.jpg",
"genre_ids": [
    878,
    27
],
"id": 1125510,
"original_language": "es",
"original_title": "El hoyo 2",
"overview": "After a mysterious leader imposes his law in a brutal system of vertical cells, a new arrival battles against a dubious food distribution method.",
"popularity": 832.715,
"poster_path": "/z2m3g8QOEMNyslgBU5vsyzRwgSz.jpg",
"release_date": "2024-09-27",
"title": "The Platform 2",
"video": false,
"vote_average": 5.7,
"vote_count": 749
},
{
"adult": false,
"backdrop_path": "/hd1TvTUGjkoYoqvXYfSBpI5Ri9B.jpg",
"genre_ids": [
    16,
    28,
    12,
    878
],
"id": 1159311,
"original_language": "ja",
"original_title": "僕のヒーローアカデミア THE MOVIE ユアネクスト",
"overview": "In a society devastated by the effects of an all-out war between heroes and villains, a mysterious giant fortress suddenly appears, engulfing towns and people one after another. Then, a man reminiscent of All Might, the 'symbol of peace', stands in front of Izuku and his friends...",
"popularity": 823.282,
"poster_path": "/8rdB1wkheEMMqcY8qLAKjCMPcnZ.jpg",
"release_date": "2024-08-02",
"title": "My Hero Academia: You're Next",
"video": false,
"vote_average": 6.758,
"vote_count": 31
},
{
"adult": false,
"backdrop_path": "/uGmYqxh8flqkudioyFtD7IJSHxK.jpg",
"genre_ids": [
    18,
    80,
    53
],
"id": 889737,
"original_language": "en",
"original_title": "Joker: Folie à Deux",
"overview": "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him.",
"popularity": 1080.437,
"poster_path": "/aciP8Km0waTLXEYf5ybFK5CSUxl.jpg",
"release_date": "2024-10-01",
"title": "Joker: Folie à Deux",
"video": false,
"vote_average": 5.76,
"vote_count": 1025
},
{
"adult": false,
"backdrop_path": "/mpMDztY5OmV7i4ypYpWgqsP4DHs.jpg",
"genre_ids": [
    27,
    53
],
"id": 978796,
"original_language": "en",
"original_title": "Bagman",
"overview": "For centuries and across cultures, parents have warned their children of the legendary Bagman, who snatches innocent children and stuffs them into his vile, rotting bag—never to be seen again. Patrick McKee narrowly escaped such an encounter as a boy, which left him with lasting scars throughout his adulthood. Now, Patrick’s childhood tormentor has returned, threatening the safety of his wife Karina and son Jake.",
"popularity": 640.261,
"poster_path": "/pkKcIP2B2ILAh4lGKyn9YkO0L1t.jpg",
"release_date": "2024-09-20",
"title": "Bagman",
"video": false,
"vote_average": 6.5,
"vote_count": 44
},
{
"adult": false,
"backdrop_path": "/cRdA9xjHBbobw4LJFsQ3j1CgpVq.jpg",
"genre_ids": [
    27,
    53
],
"id": 663712,
"original_language": "en",
"original_title": "Terrifier 2",
"overview": "A year after the Miles County massacre, Art the Clown is resurrected by a sinister entity. Art returns home, where he must hunt down and destroy teenage Sienna and her younger brother Jonathan on Halloween. As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.",
"popularity": 633.536,
"poster_path": "/8gLhu8UFPZfH2Hv11JhTZkb9CVl.jpg",
"release_date": "2022-10-06",
"title": "Terrifier 2",
"video": false,
"vote_average": 6.8,
"vote_count": 1904
},
{
"adult": false,
"backdrop_path": "/of1tQasFGCeHgWPmSgdA1WS6hNW.jpg",
"genre_ids": [
    80,
    53,
    28
],
"id": 1047373,
"original_language": "en",
"original_title": "The Silent Hour",
"overview": "While working a case as an interpreter, a hearing-impaired police detective must confront a group of criminals trying to eliminate a deaf murder witness in her apartment building.",
"popularity": 551.405,
"poster_path": "/j736cRzBtEPCm0nHnpRN1prqiqj.jpg",
"release_date": "2024-10-03",
"title": "The Silent Hour",
"video": false,
"vote_average": 6.4,
"vote_count": 41
},
{
"adult": false,
"backdrop_path": "/cVg97LOJgrDZJ7bVmjU2KsGRYnU.jpg",
"genre_ids": [
    27,
    9648
],
"id": 1100782,
"original_language": "en",
"original_title": "Smile 2",
"overview": "About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events. Overwhelmed by the escalating horrors and the pressures of fame, Skye is forced to face her dark past to regain control of her life before it spirals out of control.",
"popularity": 597.538,
"poster_path": "/aE85MnPIsSoSs3978Noo16BRsKN.jpg",
"release_date": "2024-10-16",
"title": "Smile 2",
"video": false,
"vote_average": 6.9,
"vote_count": 220
},
{
"adult": false,
"backdrop_path": "/g1z1ZvYKcmk9EnVOTYXR6vkNjkZ.jpg",
"genre_ids": [
    14,
    27,
    28
],
"id": 1087822,
"original_language": "en",
"original_title": "Hellboy: The Crooked Man",
"overview": "Hellboy and a rookie BPRD agent get stranded in 1950s rural Appalachia. There, they discover a small community haunted by witches, led by a local devil with a troubling connection to Hellboy's past: the Crooked Man.",
"popularity": 503.499,
"poster_path": "/iz2GabtToVB05gLTVSH7ZvFtsMM.jpg",
"release_date": "2024-08-29",
"title": "Hellboy: The Crooked Man",
"video": false,
"vote_average": 5.4,
"vote_count": 222
},
{
"adult": false,
"backdrop_path": "/64tinBsds1nVp4wOCgYhMbSgsRW.jpg",
"genre_ids": [
    28,
    18,
    36
],
"id": 1075676,
"original_language": "ko",
"original_title": "전,란",
"overview": "In the Joseon Dynasty, two friends who grew up together — one the master and one the servant — reunite post-war as enemies on opposing sides.",
"popularity": 499.372,
"poster_path": "/hg9OeaCRSpazrfqYyEFr6BDaZW8.jpg",
"release_date": "2024-10-02",
"title": "Uprising",
"video": false,
"vote_average": 7.212,
"vote_count": 78
},
{
"adult": false,
"backdrop_path": "/aFDYcmwEWRiEh58Ri1tMpCUWPBp.jpg",
"genre_ids": [
    10770,
    10751,
    35,
    27,
    16
],
"id": 1354627,
"original_language": "en",
"original_title": "SpongeBob Squarepants: Kreepaway Kamp",
"overview": "While at Kamp Koral for a reunion, SpongeBob and the gang are stalked by a mysterious figure lurking in the shadows as campers start disappearing one by one!",
"popularity": 518.021,
"poster_path": "/blRsgsexoBqnjcEJkV8beKAVT6J.jpg",
"release_date": "2024-10-10",
"title": "SpongeBob Squarepants: Kreepaway Kamp",
"video": false,
"vote_average": 7.026,
"vote_count": 38
},
{
"adult": false,
"backdrop_path": "/fy5HuDMPAwiGtRQlRP0zqLN3zM4.jpg",
"genre_ids": [
    27,
    53
],
"id": 1306764,
"original_language": "tl",
"original_title": "Outside",
"overview": "A family retreats to an isolated farm during a zombie outbreak, but years of painful secrets take a toll as they navigate their desolate world.",
"popularity": 329.363,
"poster_path": "/sIdczpaO0XXBe6OEIL8NbWMqQrO.jpg",
"release_date": "2024-10-17",
"title": "Outside",
"video": false,
"vote_average": 5.6,
"vote_count": 75
}
]

export const popular_movies=[{
    "adult": false,
    "backdrop_path": "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
    "genre_ids": [878, 28, 12],
    "id": 912649,
    "original_language": "en",
    "original_title": "Venom: The Last Dance",
    "overview": "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
    "popularity": 6655.644,
    "poster_path": "/k42Owka8v91trK1qMYwCQCNwJKr.jpg",
    "release_date": "2024-10-22",
    "title": "Venom: The Last Dance",
    "video": false,
    "vote_average": 6.6,
    "vote_count": 296
}, {
    "adult": false,
    "backdrop_path": "/1Oi7u3ebJbz9glmG4GV0rEZmICC.jpg",
    "genre_ids": [16, 878, 10751],
    "id": 1184918,
    "original_language": "en",
    "original_title": "The Wild Robot",
    "overview": "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    "popularity": 5274.515,
    "poster_path": "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
    "release_date": "2024-09-12",
    "title": "The Wild Robot",
    "video": false,
    "vote_average": 8.583,
    "vote_count": 1969
}, {
    "adult": false,
    "backdrop_path": "/oPUOpnl3pqD8wuidjfUn17mO1yA.jpg",
    "genre_ids": [16, 878, 12, 10751, 28],
    "id": 698687,
    "original_language": "en",
    "original_title": "Transformers One",
    "overview": "The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.",
    "popularity": 3884.457,
    "poster_path": "/qrwI2T844nrBUv3eDwQZRDdgSFs.jpg",
    "release_date": "2024-09-11",
    "title": "Transformers One",
    "video": false,
    "vote_average": 8.1,
    "vote_count": 434
}, {
    "adult": false,
    "backdrop_path": "/xlkclSE4aq7r3JsFIJRgs21zUew.jpg",
    "genre_ids": [27, 53],
    "id": 1034541,
    "original_language": "en",
    "original_title": "Terrifier 3",
    "overview": "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
    "popularity": 3997.131,
    "poster_path": "/63xYQj1BwRFielxsBDXvHIJyXVm.jpg",
    "release_date": "2024-10-09",
    "title": "Terrifier 3",
    "video": false,
    "vote_average": 7.3,
    "vote_count": 302
}, {
    "adult": false,
    "backdrop_path": "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
    "genre_ids": [878, 27],
    "id": 945961,
    "original_language": "en",
    "original_title": "Alien: Romulus",
    "overview": "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
    "popularity": 2513.291,
    "poster_path": "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    "release_date": "2024-08-13",
    "title": "Alien: Romulus",
    "video": false,
    "vote_average": 7.3,
    "vote_count": 2001
}, {
    "adult": false,
    "backdrop_path": "/9oYdz5gDoIl8h67e3ccv3OHtmm2.jpg",
    "genre_ids": [27, 878, 53],
    "id": 933260,
    "original_language": "en",
    "original_title": "The Substance",
    "overview": "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
    "popularity": 2129.397,
    "poster_path": "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
    "release_date": "2024-09-07",
    "title": "The Substance",
    "video": false,
    "vote_average": 7.3,
    "vote_count": 1017
}, {
    "adult": false,
    "backdrop_path": "/plH6vmlExhkNsxO56DKIzO3oC2O.jpg",
    "genre_ids": [53, 12, 28, 878],
    "id": 1196470,
    "original_language": "fr",
    "original_title": "Survivre",
    "overview": "A couple celebrates their son’s birthday in the middle of the ocean on their boat. A violent storm hits and it brings up hungry creatures from the depths and they fight for their survival.",
    "popularity": 1682.472,
    "poster_path": "/7fR3KxswtY8OHHZuOUB9td58CRX.jpg",
    "release_date": "2024-06-19",
    "title": "Survive",
    "video": false,
    "vote_average": 4.6,
    "vote_count": 25
}, {
    "adult": false,
    "backdrop_path": "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    "genre_ids": [28, 35, 878],
    "id": 533535,
    "original_language": "en",
    "original_title": "Deadpool \u0026 Wolverine",
    "overview": "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    "popularity": 1853.609,
    "poster_path": "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    "release_date": "2024-07-24",
    "title": "Deadpool \u0026 Wolverine",
    "video": false,
    "vote_average": 7.7,
    "vote_count": 4889
}, {
    "adult": false,
    "backdrop_path": "/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg",
    "genre_ids": [878, 28],
    "id": 335983,
    "original_language": "en",
    "original_title": "Venom",
    "overview": "Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.",
    "popularity": 1515.149,
    "poster_path": "/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
    "release_date": "2018-09-28",
    "title": "Venom",
    "video": false,
    "vote_average": 6.8,
    "vote_count": 15803
}, {
    "adult": false,
    "backdrop_path": "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
    "genre_ids": [878, 28, 12],
    "id": 580489,
    "original_language": "en",
    "original_title": "Venom: Let There Be Carnage",
    "overview": "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
    "popularity": 1504.565,
    "poster_path": "/1MJNcPZy46hIy2CmSqOeru0yr5C.jpg",
    "release_date": "2021-09-30",
    "title": "Venom: Let There Be Carnage",
    "video": false,
    "vote_average": 6.798,
    "vote_count": 10047
}, {
    "adult": false,
    "backdrop_path": "/9msuazXGWAyl7vhxVFU7e7Bb5Ik.jpg",
    "genre_ids": [18, 10749],
    "id": 179387,
    "original_language": "tl",
    "original_title": "Heavenly Touch",
    "overview": "Jonard is having trouble making ends meet. His mother is suffering from depression, and he and his sister are forced to quit school in order to take care of her. One day, Jonard meets up his friend Rodel, and Rodel introduces him to the world of massage parlors. Rodel teaches him massage, and brings him to Heavenly Touch, a syndicate-run massage parlor that mostly caters to homosexuals.",
    "popularity": 1223.024,
    "poster_path": "/ory8WuAqznTE7lfopTSymHpop2t.jpg",
    "release_date": "2009-05-12",
    "title": "Heavenly Touch",
    "video": false,
    "vote_average": 6.0,
    "vote_count": 19
}, {
    "adult": false,
    "backdrop_path": "/xi1VSt3DtkevUmzCx2mNlCoDe74.jpg",
    "genre_ids": [35, 14, 27],
    "id": 917496,
    "original_language": "en",
    "original_title": "Beetlejuice Beetlejuice",
    "overview": "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Betelgeuse, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
    "popularity": 1040.617,
    "poster_path": "/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg",
    "release_date": "2024-09-04",
    "title": "Beetlejuice Beetlejuice",
    "video": false,
    "vote_average": 7.2,
    "vote_count": 1611
}, {
    "adult": false,
    "backdrop_path": "/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg",
    "genre_ids": [16, 10751, 12, 35, 18],
    "id": 1022789,
    "original_language": "en",
    "original_title": "Inside Out 2",
    "overview": "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
    "popularity": 1143.934,
    "poster_path": "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    "release_date": "2024-06-11",
    "title": "Inside Out 2",
    "video": false,
    "vote_average": 7.6,
    "vote_count": 4525
}, {
    "adult": false,
    "backdrop_path": "/uLqNGzJwnj8JKkKuRM2dHWJKCtc.jpg",
    "genre_ids": [28, 27, 53],
    "id": 1029235,
    "original_language": "en",
    "original_title": "Azrael",
    "overview": "In a world where no one speaks, a devout female hunts down a young woman who has escaped her imprisonment. Recaptured by its ruthless leaders, Azrael is due to be sacrificed to pacify an ancient evil deep within the surrounding wilderness.",
    "popularity": 1100.796,
    "poster_path": "/qpdFKDvJS7oLKTcBLXOaMwUESbs.jpg",
    "release_date": "2024-09-27",
    "title": "Azrael",
    "video": false,
    "vote_average": 6.1,
    "vote_count": 104
}, {
    "adult": false,
    "backdrop_path": "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
    "genre_ids": [16, 10751, 35, 28],
    "id": 519182,
    "original_language": "en",
    "original_title": "Despicable Me 4",
    "overview": "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
    "popularity": 1037.43,
    "poster_path": "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
    "release_date": "2024-06-20",
    "title": "Despicable Me 4",
    "video": false,
    "vote_average": 7.112,
    "vote_count": 2074
}, {
    "adult": false,
    "backdrop_path": "/3m0j3hCS8kMAaP9El6Vy5Lqnyft.jpg",
    "genre_ids": [878, 27],
    "id": 1125510,
    "original_language": "es",
    "original_title": "El hoyo 2",
    "overview": "After a mysterious leader imposes his law in a brutal system of vertical cells, a new arrival battles against a dubious food distribution method.",
    "popularity": 832.715,
    "poster_path": "/z2m3g8QOEMNyslgBU5vsyzRwgSz.jpg",
    "release_date": "2024-09-27",
    "title": "The Platform 2",
    "video": false,
    "vote_average": 5.7,
    "vote_count": 749
}, {
    "adult": false,
    "backdrop_path": "/bAO9hLGRWOJMUFXmKwa4kST6I5N.jpg",
    "genre_ids": [28, 35, 80],
    "id": 616446,
    "original_language": "en",
    "original_title": "Brothers",
    "overview": "A reformed criminal's attempt at going straight is derailed when he reunites with his sanity-testing twin brother on a road trip for the score of a lifetime. Dodging bullets, the law, and an overbearing mother along the way, they must heal their severed family bond before they end up killing each other.",
    "popularity": 928.33,
    "poster_path": "/Akweo95FGyDpucYVT81h0SbX8Ky.jpg",
    "release_date": "2024-10-10",
    "title": "Brothers",
    "video": false,
    "vote_average": 6.3,
    "vote_count": 117
}, {
    "adult": false,
    "backdrop_path": "/hd1TvTUGjkoYoqvXYfSBpI5Ri9B.jpg",
    "genre_ids": [16, 28, 12, 878],
    "id": 1159311,
    "original_language": "ja",
    "original_title": "僕のヒーローアカデミア THE MOVIE ユアネクスト",
    "overview": "In a society devastated by the effects of an all-out war between heroes and villains, a mysterious giant fortress suddenly appears, engulfing towns and people one after another. Then, a man reminiscent of All Might, the 'symbol of peace', stands in front of Izuku and his friends...",
    "popularity": 823.282,
    "poster_path": "/8rdB1wkheEMMqcY8qLAKjCMPcnZ.jpg",
    "release_date": "2024-08-02",
    "title": "My Hero Academia: You're Next",
    "video": false,
    "vote_average": 6.8,
    "vote_count": 31
}, {
    "adult": false,
    "backdrop_path": "/pvE13VXj7WvTDYkng3tTWOTO6Nq.jpg",
    "genre_ids": [28, 80, 53],
    "id": 1151949,
    "original_language": "id",
    "original_title": "Jejak Bayangan",
    "overview": "Skilled in the art of killing, a young assassin defies her mentor to save a boy from a ruthless crime syndicate — and she'll destroy anyone in her path.",
    "popularity": 800.529,
    "poster_path": "/cfkcrKySRyJiIdLo6c6kNSyLFh7.jpg",
    "release_date": "2024-09-10",
    "title": "The Shadow Strays",
    "video": false,
    "vote_average": 7.4,
    "vote_count": 99
}, {
    "adult": false,
    "backdrop_path": "/v23fWgJUEt8EMmvn19btIacxP8E.jpg",
    "genre_ids": [10749, 14, 16],
    "id": 3933,
    "original_language": "en",
    "original_title": "Corpse Bride",
    "overview": "Set in a 19th-century European village, this stop-motion animation feature follows the story of Victor, a young man whisked away to the underworld and wed to a mysterious corpse bride, while his real bride Victoria waits bereft in the land of the living.",
    "popularity": 775.08,
    "poster_path": "/isb2Qow76GpqYmsSyfdMfsYAjts.jpg",
    "release_date": "2005-09-12",
    "title": "Corpse Bride",
    "video": false,
    "vote_average": 7.577,
    "vote_count": 9156
}]

export const trending_movies=[{
    "adult": false,
    "backdrop_path": "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    "genre_ids": [18, 80],
    "id": 278,
    "original_language": "en",
    "original_title": "The Shawshank Redemption",
    "overview": "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    "popularity": 235.92,
    "poster_path": "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    "release_date": "1994-09-23",
    "title": "The Shawshank Redemption",
    "video": false,
    "vote_average": 8.707,
    "vote_count": 27019
}, {
    "adult": false,
    "backdrop_path": "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    "genre_ids": [18, 80],
    "id": 238,
    "original_language": "en",
    "original_title": "The Godfather",
    "overview": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    "popularity": 253.46,
    "poster_path": "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    "release_date": "1972-03-14",
    "title": "The Godfather",
    "video": false,
    "vote_average": 8.7,
    "vote_count": 20520
}, {
    "adult": false,
    "backdrop_path": "/1Oi7u3ebJbz9glmG4GV0rEZmICC.jpg",
    "genre_ids": [16, 878, 10751],
    "id": 1184918,
    "original_language": "en",
    "original_title": "The Wild Robot",
    "overview": "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    "popularity": 5274.515,
    "poster_path": "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
    "release_date": "2024-09-12",
    "title": "The Wild Robot",
    "video": false,
    "vote_average": 8.6,
    "vote_count": 1967
}, {
    "adult": false,
    "backdrop_path": "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    "genre_ids": [18, 80],
    "id": 240,
    "original_language": "en",
    "original_title": "The Godfather Part II",
    "overview": "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    "popularity": 102.534,
    "poster_path": "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    "release_date": "1974-12-20",
    "title": "The Godfather Part II",
    "video": false,
    "vote_average": 8.6,
    "vote_count": 12380
}, {
    "adult": false,
    "backdrop_path": "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    "genre_ids": [18, 36, 10752],
    "id": 424,
    "original_language": "en",
    "original_title": "Schindler's List",
    "overview": "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    "popularity": 88.509,
    "poster_path": "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    "release_date": "1993-12-15",
    "title": "Schindler's List",
    "video": false,
    "vote_average": 8.6,
    "vote_count": 15785
}, {
    "adult": false,
    "backdrop_path": "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
    "genre_ids": [18],
    "id": 389,
    "original_language": "en",
    "original_title": "12 Angry Men",
    "overview": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    "popularity": 62.811,
    "poster_path": "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    "release_date": "1957-04-10",
    "title": "12 Angry Men",
    "video": false,
    "vote_average": 8.545,
    "vote_count": 8591
}, {
    "adult": false,
    "backdrop_path": "/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg",
    "genre_ids": [16, 10751, 14],
    "id": 129,
    "original_language": "ja",
    "original_title": "千と千尋の神隠し",
    "overview": "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    "popularity": 122.638,
    "poster_path": "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    "release_date": "2001-07-20",
    "title": "Spirited Away",
    "video": false,
    "vote_average": 8.538,
    "vote_count": 16428
}, {
    "adult": false,
    "backdrop_path": "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    "genre_ids": [35, 18, 10749],
    "id": 19404,
    "original_language": "hi",
    "original_title": "दिलवाले दुल्हनिया ले जायेंगे",
    "overview": "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    "popularity": 52.772,
    "poster_path": "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
    "release_date": "1995-10-20",
    "title": "Dilwale Dulhania Le Jayenge",
    "video": false,
    "vote_average": 8.5,
    "vote_count": 4431
}, {
    "adult": false,
    "backdrop_path": "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    "genre_ids": [18, 28, 80, 53],
    "id": 155,
    "original_language": "en",
    "original_title": "The Dark Knight",
    "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    "popularity": 139.862,
    "poster_path": "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    "release_date": "2008-07-16",
    "title": "The Dark Knight",
    "video": false,
    "vote_average": 8.516,
    "vote_count": 32770
}, {
    "adult": false,
    "backdrop_path": "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
    "genre_ids": [14, 18, 80],
    "id": 497,
    "original_language": "en",
    "original_title": "The Green Mile",
    "overview": "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    "popularity": 82.863,
    "poster_path": "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    "release_date": "1999-12-10",
    "title": "The Green Mile",
    "video": false,
    "vote_average": 8.507,
    "vote_count": 17340
}, {
    "adult": false,
    "backdrop_path": "/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg",
    "genre_ids": [35, 53, 18],
    "id": 496243,
    "original_language": "ko",
    "original_title": "기생충",
    "overview": "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    "popularity": 143.101,
    "poster_path": "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    "release_date": "2019-05-30",
    "title": "Parasite",
    "video": false,
    "vote_average": 8.506,
    "vote_count": 18170
}, {
    "adult": false,
    "backdrop_path": "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    "genre_ids": [53, 80],
    "id": 680,
    "original_language": "en",
    "original_title": "Pulp Fiction",
    "overview": "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    "popularity": 108.981,
    "poster_path": "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    "release_date": "1994-09-10",
    "title": "Pulp Fiction",
    "video": false,
    "vote_average": 8.488,
    "vote_count": 27802
}, {
    "adult": false,
    "backdrop_path": "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    "genre_ids": [16, 10749, 18],
    "id": 372058,
    "original_language": "ja",
    "original_title": "君の名は。",
    "overview": "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    "popularity": 117.863,
    "poster_path": "/vfJFJPepRKapMd5G2ro7klIRysq.jpg",
    "release_date": "2016-08-26",
    "title": "Your Name.",
    "video": false,
    "vote_average": 8.485,
    "vote_count": 11318
}, {
    "adult": false,
    "backdrop_path": "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    "genre_ids": [12, 14, 28],
    "id": 122,
    "original_language": "en",
    "original_title": "The Lord of the Rings: The Return of the King",
    "overview": "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
    "popularity": 165.768,
    "poster_path": "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    "release_date": "2003-12-17",
    "title": "The Lord of the Rings: The Return of the King",
    "video": false,
    "vote_average": 8.483,
    "vote_count": 24102
}, {
    "adult": false,
    "backdrop_path": "/ghgfzbEV7kbpbi1O8eIILKVXEA8.jpg",
    "genre_ids": [35, 18, 10749],
    "id": 13,
    "original_language": "en",
    "original_title": "Forrest Gump",
    "overview": "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    "popularity": 123.193,
    "poster_path": "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    "release_date": "1994-06-23",
    "title": "Forrest Gump",
    "video": false,
    "vote_average": 8.472,
    "vote_count": 27330
}, {
    "adult": false,
    "backdrop_path": "/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg",
    "genre_ids": [37],
    "id": 429,
    "original_language": "it",
    "original_title": "Il buono, il brutto, il cattivo",
    "overview": "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    "popularity": 84.364,
    "poster_path": "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    "release_date": "1966-12-22",
    "title": "The Good, the Bad and the Ugly",
    "video": false,
    "vote_average": 8.5,
    "vote_count": 8564
}, {
    "adult": false,
    "backdrop_path": "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
    "genre_ids": [28, 18],
    "id": 346,
    "original_language": "ja",
    "original_title": "七人の侍",
    "overview": "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
    "popularity": 57.389,
    "poster_path": "/iAq0sq42vKTLneVGqHn1D4GzgrM.jpg",
    "release_date": "1954-04-26",
    "title": "Seven Samurai",
    "video": false,
    "vote_average": 8.5,
    "vote_count": 3652
}, {
    "adult": false,
    "backdrop_path": "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
    "genre_ids": [18, 80],
    "id": 769,
    "original_language": "en",
    "original_title": "GoodFellas",
    "overview": "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    "popularity": 78.118,
    "poster_path": "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    "release_date": "1990-09-12",
    "title": "GoodFellas",
    "video": false,
    "vote_average": 8.5,
    "vote_count": 12796
}, {
    "adult": false,
    "backdrop_path": "/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg",
    "genre_ids": [16, 18, 10752],
    "id": 12477,
    "original_language": "ja",
    "original_title": "火垂るの墓",
    "overview": "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
    "popularity": 0.065,
    "poster_path": "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
    "release_date": "1988-04-16",
    "title": "Grave of the Fireflies",
    "video": false,
    "vote_average": 8.455,
    "vote_count": 5512
}, {
    "adult": false,
    "backdrop_path": "/7lyq8hK0MhPHpUXdnqbFvZYSfkk.jpg",
    "genre_ids": [18, 10749],
    "id": 11216,
    "original_language": "it",
    "original_title": "Nuovo Cinema Paradiso",
    "overview": "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    "popularity": 34.6,
    "poster_path": "/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg",
    "release_date": "1988-11-17",
    "title": "Cinema Paradiso",
    "video": false,
    "vote_average": 8.4,
    "vote_count": 4343
}]